[build]
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "18"
CI = "false"
GENERATE_SOURCEMAP = "false"

[[redirects]]
from = "https://coraliealexandru.netlify.app/*"
to = "https://coraliealexandru.fr/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200